// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDmXt5vd57qehGgQRuhDeN78ZijhBBm0E',
    appId: '1:617524017235:web:d4a03d01cf903139cceea6',
    messagingSenderId: '617524017235',
    projectId: 'solace-c17a5',
    authDomain: 'solace-c17a5.firebaseapp.com',
    storageBucket: 'solace-c17a5.firebasestorage.app',
    measurementId: 'G-PD7GT3EJ7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_mi2LwLkW4GhbIz_8BYRmpldyx_2JmA',
    appId: '1:617524017235:android:b08e023a46542b68cceea6',
    messagingSenderId: '617524017235',
    projectId: 'solace-c17a5',
    storageBucket: 'solace-c17a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTO89C-5GJd32rLIV6KE6qyF4Q4Bws2WU',
    appId: '1:617524017235:ios:77c4d401b628d25bcceea6',
    messagingSenderId: '617524017235',
    projectId: 'solace-c17a5',
    storageBucket: 'solace-c17a5.firebasestorage.app',
    iosClientId: '617524017235-3l93sfpcrenf9a9hscclf17ver3q33f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.solace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTO89C-5GJd32rLIV6KE6qyF4Q4Bws2WU',
    appId: '1:617524017235:ios:77c4d401b628d25bcceea6',
    messagingSenderId: '617524017235',
    projectId: 'solace-c17a5',
    storageBucket: 'solace-c17a5.firebasestorage.app',
    iosClientId: '617524017235-3l93sfpcrenf9a9hscclf17ver3q33f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.solace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDmXt5vd57qehGgQRuhDeN78ZijhBBm0E',
    appId: '1:617524017235:web:61eb0da118403040cceea6',
    messagingSenderId: '617524017235',
    projectId: 'solace-c17a5',
    authDomain: 'solace-c17a5.firebaseapp.com',
    storageBucket: 'solace-c17a5.firebasestorage.app',
    measurementId: 'G-YNMMJDT3NW',
  );
}
